Update google provider 4.x
mineiros-io/terraform-google-storage-bucket pull request #12
Opened 2021-12-08 01:52 UTC by thiesen

2021-12-10 03:40 UTC, mariux requested changes
depending module needs to be updated first as this will prevent using this module with 4.x

2021-12-13 11:56 UTC, soerenmartius requested changes
lgtm!

2021-12-13 11:56 UTC, soerenmartius approved these changes
lgtm!

2021-12-13 13:01 UTC, mariux approved these changes

2021-12-13 13:02 UTC, merged